StartupEvents.registry('item', event => {
    // eye of air items
    event.create('gravitite_gel')
        .displayName('Gravitite Gel')
        .maxStackSize(16)
        .tooltip('Feels very light')
    event.create('valkyrean_wing')
        .displayName('Valkyrean Wing')
        .maxStackSize(16)
        .tooltip('Still tense with fierceness')
    event.create('solar_stone')
        .displayName('Solar Stone')
        .maxStackSize(16)
        .tooltip('Hot to the touch')
    event.create('whale_wind')
        .displayName('Whale Wind')
        .maxStackSize(16)
        .tooltip('Strong gust that never stops blowing')
    // eye of bones items
    event.create('green_goop')
        .displayName('Green Goop')
        .maxStackSize(16)
        .tooltip('Hurts to hold')
    event.create('stiff_skin')
        .displayName('Stiff Skin')
        .maxStackSize(16)
        .tooltip('Hardened almost to stone')
    event.create('golden_egg')
        .displayName('Golden Egg')
        .maxStackSize(16)
        .tooltip('Holds potential for life')
    // eye of magma and soul items 
    // (not used to craft it, but to summon stalwart dungeon bosses that drop it)
    event.create('ghast_key')
        .displayName('Ghast Key')
        .maxStackSize(16)
        .tooltip('Unlocks the cage of a ghastly guardian')
    event.create('keeper_key')
        .displayName('Keeper Key')
        .maxStackSize(16)
        .tooltip('Unlocks the cage of a cunning keeper')
})

